apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-nfs
  labels:
    type: local
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "/srv/nfs/kube"
    server: 172.16.16.100
